service: hospital-api

provider:
  name: aws
  runtime: nodejs20.x

functions:
  api:
    handler: src/handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
    reloadHandler: True
